name: hyoom's hacking blog
description: pwnable, reversing, coding.. 
meta_description: "hyoom's hacking blog"

markdown: kramdown
highlighter: rouge
highlight:
  line_number: true
logo: true
paginate: 15
baseurl: /
domain_name: 'http://hyoom1024.github.io'
google_analytics: 'UA-128578957-1'
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]

# Details for the RSS feed generator
url:            'http://hyoom1024.github.io'
author:         'hyoom'
